### ISSUE TITLE
[LLVM_jll] v13.0.1+3 on julia 1.8.5 throws an `ArgumentError`

### ISSUE THREAD

**Issue by Seelengrab** [JuliaPackaging/Yggdrasil#8856]
As observed here: https://github.com/JuliaPerf/MCAnalyzer.jl/actions/runs/9406622087/job/25910502181#step:6:45

This seems to be because https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/blob/LLVM-v13.0.1%2B3/.pkg/select_artifacts.jl uses TOML, but nothing puts that on the LOAD_PATH in 1.8.5 :thinking:

**Comment by vchuravy** [comment]
I think this was fixed in 1.9, but for 1.8 https://github.com/JuliaPackaging/JLLWrappers.jl/pull/35#discussion_r779956552

**Comment by Seelengrab** [comment]
I can try to make a PR to the LLVM_jll repo, is it just adding TOML as a dependency and rebuilding so we get v13.0.1+4?

**Comment by imciner2** [comment]
Is there anything that needs to be done for this in Yggdrasil, or should this be moved to a different repo?

**Comment by Seelengrab** [comment]
I have no idea - since the original issue is due to a JLL, I opened it here. I'm not familiar enough with the internals of a JLL package to say where/how this should be fixed. I'm just getting annoyed by the CI I set up for MCAnalyzer.jl that now tells me every week that this is still broken...

**Comment by ViralBShah** [comment]
Can we close this?

**Comment by imciner2** [comment]
Closing, we have moved past LLVM 13 now, and nothing seems to have been suggested as a fix.
